### ISSUE TITLE
Link to koa-docs

### ISSUE THREAD

**Issue by a-s-o** [koajs/joi-router#10]
Hello,

Great job on this project. I really like the declarative route specs you have created and some really good forethought went into exposing the routes for analysis and having a meta property.

I am building a number of micro-services and want some documentation to go along with them so I have created a small project that renders documentation from the route specs provided by `koa-joi-router`. The project is [koa-docs](https://github.com/a-s-o/koa-docs). I would appreciate a link from here so more people can use/contribute to it.

Thanks

**Comment by aheckmann** [comment]
linked!
