### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by jasonlewicki** [koajs/joi-router#115]
Not sure which repo this goes in:

```
node_modules/@types/koa-joi-router/index.d.ts:29:53 - error TS2694: Namespace 'Application' has no exported member 'Next'.

29     type FullHandler = (ctx: Koa.Context, next: Koa.Next) => any;
                                               ~~~~


Found 1 error.
```

**Comment by 3imed-jaberi** [comment]
@jasonlewicki, this error comes from`@types/koa-joi-router` due to not be use the right type of handler. You can find the right type [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L539).
