### ISSUE TITLE
Plan to support Joi validation object in addition to definition?

### ISSUE THREAD

**Issue by eizzo** [koajs/joi-router#18]
It appears the header, query, params, and body properties of the validate object in route() options do not support a Joi schema object as generated by Joi.compile(). Any plans to support Joi schema objects in these cases? Thanks.

**Comment by aheckmann** [comment]
happy to support it / surprised it isn't supported since we pass these values to `Joi.validate`. Can you paste an example?

**Comment by aheckmann** [comment]
no response. closing
