### ISSUE TITLE
Setting converted query values is not working correctly

### ISSUE THREAD

**Issue by satazor** [koajs/joi-router#21]
Joi supports converting/casting types but this feature is not working correctly with the koa integration.

If one has a `query` validator, [this](https://github.com/koajs/joi-router/blob/master/joi-router.js#L401) line sets request.query to the converted object but it then gets stringified again [here](https://github.com/koajs/koa/blob/master/lib/request.js#L161) which causes numbers, booleans, etc to be converted to string again.

**Comment by aheckmann** [comment]
I think this is the same as #6

**Comment by satazor** [comment]
I think it's related yes.
