### ISSUE TITLE
Will joi-router add language support?

### ISSUE THREAD

**Issue by miserylee** [koajs/joi-router#32]
As in [joi](https://github.com/hapijs/joi/blob/v9.0.4/API.md#validatevalue-schema-options-callback) document, the validate method receives 4 params.
`validate(value, schema, [options], [callback])`

Some options in validation is useful like `language - overrides individual error messages. Defaults to no override ({}). Messages apply the following rules :`

So will joi-router add `options` support in the future when use the `validate` method? 😋

**Comment by miserylee** [comment]
I'm Chinese, so in my app, I want to override the default `language` options to Chinese. That will be much helpful!

**Comment by aheckmann** [comment]
good idea. please open a PR with a prototype.

**Comment by 3imed-jaberi** [comment]
@aheckmann, please close this issue it fixed with #119.

**Comment by aheckmann** [comment]
thanks!
