### ISSUE TITLE
Build issue using v 4.0.0 due to dependency on your koa-router fork?

### ISSUE THREAD

**Issue by mdgbayly** [koajs/joi-router#39]
We are still using version 4.0.0 of this package which has a specific commit dependency on your fork of koa-router:

git+https://github.com/aheckmann/koa-router.git#f0c60d374b5903f

This has started breaking in our recent builds.  Is it possible you changed something on your fork that would break this?

When we try and npm install we get a git error:

    npm info git [ 'rev-list', '-n1', 'f0c60d374b5903f' ]
    npm ERR! git rev-list -n1 f0c60d374b5903f: fatal: ambiguous argument 'f0c60d374b5903f': unknown     revision or path not in the working tree.

We can see that commit in github, but it does not seem to appear in any branch?

**Comment by sahal** [comment]
Forked a support branch with that points to a working koa-router dependency:

- https://github.com/sahal/joi-router/commit/5d574d20bb4cc3905a202ae0ea32b84e8597356c

Use it in your package.json when depending on joi-router tagged at 4.0.0:
`    "koa-joi-router": "git+https://github.com/sahal/joi-router.git#support/4.0.0",`

**Comment by nilgradisnik** [comment]
What's the rationale for using that fork in the first place, can't we just the official release? 😕

**Comment by aheckmann** [comment]
Released 5.1.0 which now includes koa-router 7.3.0. 

We were previously using a forked version because a [params fix](https://github.com/aheckmann/koa-router/commit/19e60d915a948c93a728ecbd90b92060b1206f24) hadn't been merged/released in koa-router.
