### ISSUE TITLE
ctx._matchedRoute undefined

### ISSUE THREAD

**Issue by willin** [koajs/joi-router#53]
When a route is matched, its path is available at ctx._matchedRoute and if named, the name is available at ctx._matchedRouteName

https://github.com/koajs/joi-router/blob/master/package.json#L44

@aheckmann

**Comment by aheckmann** [comment]
Those properties are not supported by this project. They are internal features of [koa-router](https://github.com/alexmingoia/koa-router) (and should probably be exposed on [`ctx.state`](http://koajs.com/#ctx-state)). That said, the next release of this project includes an updated `koa-router`.
