### ISSUE TITLE
install error with security connect problem ( in China )

### ISSUE THREAD

**Issue by zouyixiong** [koajs/joi-router#61]
I can't install this package, with error: ( in China ,  it's OK in AWS us)
```
$ npm -v
5.4.2
$ npm install koa-joi-router
npm WARN deprecated clone@1.0.2: XSS vulnerability fixed in v1.0.3
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/aheckmann/koa-router.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/aheckmann/koa-router.git/': Unable to communicate securely with peer: requested domain name does not match the server's certificate.
npm ERR! 
npm ERR! exited with error code: 128
```

By the way, I found the dependency version is very old compare to the original, can you upgrade it ?
And I wonder why not depend on the original `koa-router` ?

1. dependency in package.json is : ` "koa-router": "git+https://github.com/aheckmann/koa-router.git#19e60d9"`
2. `https://github.com/aheckmann/koa-router` is now in version `5.1.2`.
3.  `https://github.com/alexmingoia/koa-router` ( the original )  is now `7.3.0`.

**Comment by aheckmann** [comment]
Closing. See https://github.com/koajs/joi-router/issues/52#issuecomment-354850579
