### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by zhaoyao91** [koajs/joi-router#78]
Noticed that it's almost 10 months without any update. The major version of Joi is already 14 but that of the bundled one is just 10. 

Anyway, great package with nice design!

**Comment by richthegeek** [comment]
@aheckmann can you provide some updates on this project? I'm happy to provide PRs to update things to latest but it seems things are just ignored nowadays?

**Comment by aheckmann** [comment]
thank you @zhaoyao91 

it's not actively ignored, it's just how many free open source projects are :) my time is limited so if i do find myself with time _and_ motivation to work on it, i do, but that doesn't happen too often these days as it's not something i'm using at work right now
