### ISSUE TITLE
Trustworthiness of koa-router dependency

### ISSUE THREAD

**Issue by javiertury** [koajs/joi-router#82]
[https://github.com/nodejs/package-maintenance/issues/77#issuecomment-463356844](Take a look at this comment) and [this HN thread](https://news.ycombinator.com/item?id=19156707).

@alexmingoia has sold the koa-router repo to an unknown developer. This package depends on it.

**Comment by aheckmann** [comment]
Thanks. Yeah, saw that too. We are currently using a pinned version though
so for now I'm feeling ok.
