### ISSUE TITLE
fn is not run before specific route when using router.use(path, fn)

### ISSUE THREAD

**Issue by wdanxna** [koajs/joi-router#83]
Document says:
> To run middleware before a specific route, also pass the optional path:
> ```javascript
> const router = require('koa-joi-router');
> const users = router();
> 
> users.get('/:id', handler);
> users.use('/:id', runThisBeforeHandler);```

but `runThisBeforeHandler` is actually run **after** `handler`

**Comment by aheckmann** [comment]
fixed the docs
