### ISSUE TITLE
XSS vulnerability detected in `clone` package

### ISSUE THREAD

**Issue by piyushchauhan2011** [koajs/joi-router#95]
I found that `clone` package recently got detected with `XSS vulnerability detected`.

It would be nice to have it replaced, please check it on `npm` here: https://www.npmjs.com/package/clone

<img width="891" alt="Screenshot 2019-08-28 at 17 36 48" src="https://user-images.githubusercontent.com/693487/63848761-af150080-c9ba-11e9-93c7-4057c6e2a769.png">

**Comment by aheckmann** [comment]
only xss issue i see was closes a long time ago in a previous release https://github.com/pvorb/clone#2017-11-08 What are you seeing?

**Comment by piyushchauhan2011** [comment]
I think this issue can be closed as now xss vulnerability is not visible on npm, was only worried about it @aheckmann

**Comment by milofultz** [comment]
I'm seeing it on the page as of 20220321:

<img width="743" alt="Screen Shot 2022-03-21 at 10 10 26 AM" src="https://user-images.githubusercontent.com/65684361/159355576-5e67b3d3-738d-44bc-919a-6671569de792.png">
