### ISSUE TITLE
5->6 migration guide

### ISSUE THREAD

**Issue by oprogramador** [koajs/joi-router#96]
Could you write release notes, explaining how to upgrade `joi-router` from v5 to v6?

**Comment by warapitiya** [comment]
No changelog also. Is there a place I can see the changelog?

**Comment by aheckmann** [comment]
https://github.com/koajs/joi-router/blob/master/History.md#600--2019-04-27

The only reason for the major version was due to bumping the major version of [@hapi/joi](https://github.com/hapijs/joi) from 14.x -> 15.x, which is part of our API.
